[package]
name = "anode"
version = "0.1.0"
authors = ["::::::::::::::: <sergystepanov@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.9.0"
actix-rt = "1.0.0"
actix-codec = "0.2.0"
actix-web = "2.0.0"
actix-web-actors = "2.0.0"
actix-files = "0.2.1"
awc = "1.0.1"
log = "0.4.11"
env_logger = "0.7"
futures = "0.3.1"
bytes = "0.5.3"
