[package]
name = "anode"
version = "0.1.0"
authors = ["::::::::::::::: <sergystepanov@gmail.com>"]
edition = "2018"

[dependencies]
# a network server
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-files = "0.2.2"
env_logger = "0.7"
